### ISSUE TITLE
加速する機能？！

### ISSUE THREAD

**Issue by c2cb** [c0b21021c3/ProjExD#16]
https://github.com/c0b21021c3/ProjExD/blob/3e4aef6c8a16dca5ee9ee321d6b750bc6b9e1b7d/ex04/dodge_bomb.py#L59

爆弾が加速する機能とてもすごいと思います。
爆弾が壁に当たった際に分裂する発想も面白そうです。そしたらこうかとんは四面楚歌なので、手がお空きの際、こうかとんにも加速させることができる機能があればもっとおもしろそうです。応援しています！

**Comment by Yawn-MP** [comment]
爆弾の追加機能いいですね。ぜひやってみたいものです。こーかとんの加速はですね、じつはもうあるのですよ。コメントアウトが分かりにくかったかもですね。一応、そこだけ修正しておきます
