### ISSUE TITLE
こうかとんに当たったら跳ね返る技術

### ISSUE THREAD

**Issue by c2cb** [c0b21021c3/ProjExD#17]
https://github.com/c0b21021c3/ProjExD/blob/0300c5e95364b944c34c5dcc251002ee156bbff8/ex05/fight_kokaton.py#L74

リード三―から分かるように、こうかとんにあかちゃんを守る発想が素晴らしいと思います！！
そして実現させる技術にあっぱれです…全部参考になります、これからも応援しています！

**Comment by Yawn-MP** [comment]
実はこの機能は逆の発想でした。
と言いますのも、本来はミニこうかとんを、操作する方のこうかとんの周囲を衛星のように周ることで、爆弾から身を守る盾としようとしていたのです。しかし、衛星軌道で回すほうほうが分からず、急遽このようになりました。ラスト２０分の発想の転換です。結構ぎりぎりで危なかったと思っています。
