### ISSUE TITLE
勉強になりました。

### ISSUE THREAD

**Issue by RenNakasato** [c0b21021c3/ProjExD#19]
https://github.com/c0b21021c3/ProjExD/blob/0300c5e95364b944c34c5dcc251002ee156bbff8/ex05/fight_kokaton.py#L113
爆弾の追加に悩んでいたので、勉強になりました。

**Comment by Yawn-MP** [comment]
自分も今日ふと気が付いたやり方です、、、。参考になったとのことで、幸甚の極みにございます。
