### ISSUE TITLE
ACボタン？！

### ISSUE THREAD

**Issue by c2cb** [c0b21021c3/ProjExD#5]
https://github.com/c0b21021c3/ProjExD/blob/bd184e966ce9ce5ecfb80e4f4a08bb7c384ad300/ex02/calc.py#L65

**Comment by Yawn-MP** [comment]
Cボタンの機能をスマホなどの電卓のそれと比べたとき、その機能と同等に作れなかったと思い、同等だと感じたACボタンの名前を借りました。元はCにしたかったです
