### ISSUE TITLE
ACボタン？！ランダム？！

### ISSUE THREAD

**Issue by c2cb** [c0b21021c3/ProjExD#8]
https://github.com/c0b21021c3/ProjExD/blob/bd184e966ce9ce5ecfb80e4f4a08bb7c384ad300/ex02/calc.py#L65

明らかに授業の技術外のことをやっていますね。すごいです、正直何がどうなっているのかよく分かりません。これはもう、参考書です。あわよくば参考書のように、一行一行に解説を入れて欲しいです。あくまでも願望なので、スルーして結構です。
あなたは、柔軟な発想と実現できる技術を持った素晴らしい人間です。ぜひこのまま、のびのびと知識を吸収して、ドキドキしながらプログラミングをして、地球を美しくしてください。

**Comment by Yawn-MP** [comment]
有難うございます。べた褒めですね……さすがに地球を美しくするには至れない気もしますが、何事も積み重ねらしいので、そういう未来も無きにしも非ずかもですね
