### ISSUE TITLE
見た目にまで気にしていてすごいと思いました。

### ISSUE THREAD

**Issue by RenNakasato** [c0b21021c3/ProjExD#9]
https://github.com/c0b21021c3/ProjExD/blob/bd184e966ce9ce5ecfb80e4f4a08bb7c384ad300/ex02/calc.py#L46

**Comment by Yawn-MP** [comment]
そうなんです！こだわってます！L字にオレンジのライン、太さも統一感出して一本の線に見えるように工夫しました。
